### ISSUE TITLE
z-index too low for modal dialog box

### ISSUE THREAD

**Issue by sinanasiriamirbande** [Agranom/ngx-material-timepicker#309]

**Comment by Agranom** [comment]
you can override it in you global styles

**Comment by exitlol** [comment]
> you can override it in you global styles

I've set up a "custom css" in my global styles.scss, but it's overwritten by the default.

**Comment by sglvladi** [comment]
Managed to get around this by setting:

``` css
.timepicker-backdrop-overlay{
    z-index: 1000 !important;
}

.timepicker-overlay{
    z-index: 1000 !important;
}
```

You need to set ```!important``` otherwise it gets overridden. Hope this helps.
